# Generated by Django 3.1.7 on 2021-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donor',
            name='Blood_group',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
