# Generated by Django 3.1.7 on 2021-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodsection', '0002_blood_donor_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donor',
            name='imag',
            field=models.ImageField(default='default1.jpg', upload_to='blood_donors_pics'),
        ),
    ]
