# Generated by Django 3.1.7 on 2021-03-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='a_time',
            new_name='s_time',
        ),
    ]
