# Generated by Django 3.1.7 on 2021-03-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roombook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_booker_email', models.EmailField(max_length=254)),
                ('room_category', models.CharField(max_length=50)),
                ('room_booking_date', models.DateField(auto_now_add=True)),
                ('room_booking_for_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
